name: CI

on:
    push: {branches: [ "master" ]}
    pull_request: { branches: ["master"]}
    workflow_dispatch:
       
defaults:
    run:
        working-directory: my-ui

jobs:
  ui-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: my-ui/yarn.lock

      - name: Install
        run: yarn install --frozen-lockfile
        working-directory: my-ui

      - name: Type check
        run: yarn tsc --noEmit
        working-directory: my-ui

      - name: Unit tests
        run: yarn test

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Storybook test-runner (a11y + interactions)
        run: |
          npx http-server storybook-static -p 6006 &
          npx wait-on http://localhost:6006
          npx test-storybook --url http://localhost:6006

      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: storybook-static
